/** Curated chat emoji catalog with searchable names. */

export const EMOJI_LIST = [
  { e: '😀', n: 'grinning face smile happy' },
  { e: '😃', n: 'grinning big eyes smile happy' },
  { e: '😄', n: 'grinning smiling eyes happy laugh' },
  { e: '😁', n: 'beaming smiling eyes grin' },
  { e: '😆', n: 'grinning squinting laugh' },
  { e: '😅', n: 'grinning sweat nervous laugh' },
  { e: '🤣', n: 'rolling on the floor laughing rofl' },
  { e: '😂', n: 'tears of joy laugh cry' },
  { e: '🙂', n: 'slightly smiling' },
  { e: '🙃', n: 'upside down smile' },
  { e: '😉', n: 'winking face wink' },
  { e: '😊', n: 'smiling blush happy' },
  { e: '😇', n: 'smiling halo angel' },
  { e: '🥰', n: 'smiling hearts love' },
  { e: '😍', n: 'heart eyes love crush' },
  { e: '🤩', n: 'star struck wow' },
  { e: '😘', n: 'blowing a kiss love' },
  { e: '😗', n: 'kissing face' },
  { e: '☺️', n: 'smiling face' },
  { e: '😚', n: 'kissing closed eyes' },
  { e: '😙', n: 'kissing smiling eyes' },
  { e: '🥲', n: 'smiling tear bittersweet' },
  { e: '😋', n: 'savoring food yum' },
  { e: '😛', n: 'tongue out' },
  { e: '😜', n: 'winking tongue' },
  { e: '🤪', n: 'zany goofy' },
  { e: '😝', n: 'squinting tongue' },
  { e: '🤑', n: 'money mouth rich' },
  { e: '🤗', n: 'hugging hug' },
  { e: '🤭', n: 'hand over mouth giggle' },
  { e: '🤫', n: 'shushing quiet secret' },
  { e: '🤔', n: 'thinking hmm' },
  { e: '🤐', n: 'zipper mouth silent' },
  { e: '🤨', n: 'raised eyebrow skeptic' },
  { e: '😐', n: 'neutral face meh' },
  { e: '😑', n: 'expressionless' },
  { e: '😶', n: 'without mouth silent' },
  { e: '😏', n: 'smirking smirk' },
  { e: '😒', n: 'unamused annoyed' },
  { e: '🙄', n: 'rolling eyes' },
  { e: '😬', n: 'grimacing awkward' },
  { e: '😮‍💨', n: 'exhaling sigh relief' },
  { e: '🤥', n: 'lying pinocchio' },
  { e: '😌', n: 'relieved calm' },
  { e: '😔', n: 'pensive sad' },
  { e: '😪', n: 'sleepy tired' },
  { e: '🤤', n: 'drooling' },
  { e: '😴', n: 'sleeping sleep zzz' },
  { e: '😷', n: 'medical mask sick' },
  { e: '🤒', n: 'thermometer fever sick' },
  { e: '🤕', n: 'head bandage hurt' },
  { e: '🤢', n: 'nauseated sick' },
  { e: '🤮', n: 'vomiting sick' },
  { e: '🤧', n: 'sneezing sneeze' },
  { e: '🥵', n: 'hot face heat' },
  { e: '🥶', n: 'cold face freeze' },
  { e: '🥴', n: 'woozy dizzy' },
  { e: '😵', n: 'dizzy face' },
  { e: '🤯', n: 'exploding head mind blown' },
  { e: '🤠', n: 'cowboy hat' },
  { e: '🥳', n: 'partying celebrate party' },
  { e: '🥸', n: 'disguise glasses' },
  { e: '😎', n: 'sunglasses cool' },
  { e: '🤓', n: 'nerd glasses' },
  { e: '🧐', n: 'monocle curious' },
  { e: '😕', n: 'confused' },
  { e: '😟', n: 'worried' },
  { e: '🙁', n: 'slightly frowning sad' },
  { e: '☹️', n: 'frowning sad' },
  { e: '😮', n: 'open mouth surprised' },
  { e: '😯', n: 'hushed surprised' },
  { e: '😲', n: 'astonished shocked' },
  { e: '😳', n: 'flushed embarrassed' },
  { e: '🥺', n: 'pleading puppy eyes' },
  { e: '😦', n: 'frowning open mouth' },
  { e: '😧', n: 'anguished' },
  { e: '😨', n: 'fearful scared' },
  { e: '😰', n: 'anxious sweat' },
  { e: '😥', n: 'sad but relieved' },
  { e: '😢', n: 'crying cry sad' },
  { e: '😭', n: 'loudly crying sob' },
  { e: '😱', n: 'screaming in fear scream' },
  { e: '😖', n: 'confounded' },
  { e: '😣', n: 'persevering' },
  { e: '😞', n: 'disappointed sad' },
  { e: '😓', n: 'downcast sweat' },
  { e: '😩', n: 'weary tired' },
  { e: '😫', n: 'tired face' },
  { e: '🥱', n: 'yawning yawn' },
  { e: '😤', n: 'steam from nose proud huff' },
  { e: '😡', n: 'pouting angry mad' },
  { e: '😠', n: 'angry mad' },
  { e: '🤬', n: 'swearing cursing mad' },
  { e: '😈', n: 'smiling horns devil' },
  { e: '👿', n: 'angry horns devil' },
  { e: '💀', n: 'skull dead' },
  { e: '☠️', n: 'skull and crossbones' },
  { e: '💩', n: 'pile of poo poop' },
  { e: '🤡', n: 'clown' },
  { e: '👹', n: 'ogre' },
  { e: '👺', n: 'goblin' },
  { e: '👻', n: 'ghost boo' },
  { e: '👽', n: 'alien' },
  { e: '👾', n: 'alien monster space' },
  { e: '🤖', n: 'robot' },
  { e: '😺', n: 'grinning cat' },
  { e: '😸', n: 'grinning cat smiling' },
  { e: '😹', n: 'cat tears of joy' },
  { e: '😻', n: 'cat heart eyes' },
  { e: '😼', n: 'cat smirk' },
  { e: '😽', n: 'kissing cat' },
  { e: '🙀', n: 'weary cat' },
  { e: '😿', n: 'crying cat' },
  { e: '😾', n: 'pouting cat' },
  { e: '🙈', n: 'see no evil monkey' },
  { e: '🙉', n: 'hear no evil monkey' },
  { e: '🙊', n: 'speak no evil monkey' },
  { e: '👋', n: 'waving hand wave hello bye' },
  { e: '🤚', n: 'raised back of hand' },
  { e: '🖐️', n: 'hand splayed' },
  { e: '✋', n: 'raised hand stop' },
  { e: '🖖', n: 'vulcan salute' },
  { e: '👌', n: 'ok hand' },
  { e: '🤌', n: 'pinched fingers' },
  { e: '🤏', n: 'pinching hand small' },
  { e: '✌️', n: 'victory peace' },
  { e: '🤞', n: 'crossed fingers luck' },
  { e: '🤟', n: 'love you gesture' },
  { e: '🤘', n: 'sign of the horns rock' },
  { e: '🤙', n: 'call me hand' },
  { e: '👈', n: 'backhand left point' },
  { e: '👉', n: 'backhand right point' },
  { e: '👆', n: 'backhand up point' },
  { e: '🖕', n: 'middle finger' },
  { e: '👇', n: 'backhand down point' },
  { e: '☝️', n: 'index pointing up' },
  { e: '👍', n: 'thumbs up like yes' },
  { e: '👎', n: 'thumbs down dislike no' },
  { e: '✊', n: 'raised fist' },
  { e: '👊', n: 'oncoming fist punch' },
  { e: '🤛', n: 'left facing fist' },
  { e: '🤜', n: 'right facing fist' },
  { e: '👏', n: 'clapping hands clap applause' },
  { e: '🙌', n: 'raising hands celebrate' },
  { e: '👐', n: 'open hands' },
  { e: '🤲', n: 'palms up together' },
  { e: '🤝', n: 'handshake deal' },
  { e: '🙏', n: 'folded hands please thanks pray' },
  { e: '✍️', n: 'writing hand write' },
  { e: '💅', n: 'nail polish' },
  { e: '🤳', n: 'selfie' },
  { e: '💪', n: 'flexed biceps strong' },
  { e: '🦾', n: 'mechanical arm' },
  { e: '🦿', n: 'mechanical leg' },
  { e: '🦵', n: 'leg' },
  { e: '🦶', n: 'foot' },
  { e: '👂', n: 'ear' },
  { e: '🦻', n: 'ear with hearing aid' },
  { e: '👃', n: 'nose' },
  { e: '🧠', n: 'brain smart' },
  { e: '🫀', n: 'anatomical heart' },
  { e: '🫁', n: 'lungs' },
  { e: '🦷', n: 'tooth' },
  { e: '🦴', n: 'bone' },
  { e: '👀', n: 'eyes look see' },
  { e: '👁️', n: 'eye' },
  { e: '👅', n: 'tongue' },
  { e: '👄', n: 'mouth lips' },
  { e: '💋', n: 'kiss mark lips' },
  { e: '💘', n: 'heart with arrow love' },
  { e: '💝', n: 'heart with ribbon' },
  { e: '💖', n: 'sparkling heart' },
  { e: '💗', n: 'growing heart' },
  { e: '💓', n: 'beating heart' },
  { e: '💞', n: 'revolving hearts' },
  { e: '💕', n: 'two hearts love' },
  { e: '💟', n: 'heart decoration' },
  { e: '❣️', n: 'heart exclamation' },
  { e: '💔', n: 'broken heart' },
  { e: '❤️', n: 'red heart love' },
  { e: '🧡', n: 'orange heart' },
  { e: '💛', n: 'yellow heart' },
  { e: '💚', n: 'green heart' },
  { e: '💙', n: 'blue heart' },
  { e: '💜', n: 'purple heart' },
  { e: '🤎', n: 'brown heart' },
  { e: '🖤', n: 'black heart' },
  { e: '🤍', n: 'white heart' },
  { e: '💯', n: 'hundred points 100' },
  { e: '💢', n: 'anger symbol' },
  { e: '💥', n: 'collision boom' },
  { e: '💫', n: 'dizzy star' },
  { e: '💦', n: 'sweat droplets' },
  { e: '💨', n: 'dashing away wind' },
  { e: '🕳️', n: 'hole' },
  { e: '💣', n: 'bomb' },
  { e: '💬', n: 'speech balloon chat' },
  { e: '👁️‍🗨️', n: 'eye in speech bubble' },
  { e: '🗨️', n: 'left speech bubble' },
  { e: '🗯️', n: 'right anger bubble' },
  { e: '💭', n: 'thought balloon' },
  { e: '💤', n: 'zzz sleep' },
  { e: '👋', n: 'wave' },
  { e: '🎉', n: 'party popper celebrate' },
  { e: '🎊', n: 'confetti ball' },
  { e: '🎈', n: 'balloon' },
  { e: '🎁', n: 'wrapped gift present' },
  { e: '🏆', n: 'trophy win' },
  { e: '🥇', n: 'gold medal first' },
  { e: '🥈', n: 'silver medal second' },
  { e: '🥉', n: 'bronze medal third' },
  { e: '⚽', n: 'soccer ball football' },
  { e: '🏀', n: 'basketball' },
  { e: '🏈', n: 'american football' },
  { e: '⚾', n: 'baseball' },
  { e: '🎾', n: 'tennis' },
  { e: '🏐', n: 'volleyball' },
  { e: '🏉', n: 'rugby' },
  { e: '🎱', n: 'pool 8 ball' },
  { e: '🏓', n: 'ping pong' },
  { e: '🏸', n: 'badminton' },
  { e: '🥅', n: 'goal net' },
  { e: '⛳', n: 'flag in hole golf' },
  { e: '🏹', n: 'bow and arrow' },
  { e: '🎣', n: 'fishing pole' },
  { e: '🤿', n: 'diving mask' },
  { e: '🥊', n: 'boxing glove' },
  { e: '🥋', n: 'martial arts uniform' },
  { e: '🎽', n: 'running shirt' },
  { e: '🛹', n: 'skateboard' },
  { e: '🛼', n: 'roller skate' },
  { e: '🛷', n: 'sled' },
  { e: '⛸️', n: 'ice skate' },
  { e: '🥌', n: 'curling stone' },
  { e: '🎿', n: 'skis' },
  { e: '⛷️', n: 'skier' },
  { e: '🏂', n: 'snowboarder' },
  { e: '🪂', n: 'parachute' },
  { e: '🏋️', n: 'person lifting weights gym' },
  { e: '🤸', n: 'person cartwheeling' },
  { e: '🤼', n: 'people wrestling' },
  { e: '🤽', n: 'water polo' },
  { e: '🤾', n: 'handball' },
  { e: '🤹', n: 'juggling' },
  { e: '🧘', n: 'lotus position yoga' },
  { e: '🏄', n: 'surfing' },
  { e: '🏊', n: 'swimming' },
  { e: '🤽‍♂️', n: 'man water polo' },
  { e: '🚴', n: 'biking bicycle' },
  { e: '🚵', n: 'mountain biking' },
  { e: '🏇', n: 'horse racing' },
  { e: '🎮', n: 'video game controller gaming' },
  { e: '🕹️', n: 'joystick' },
  { e: '🎲', n: 'game die dice' },
  { e: '🧩', n: 'puzzle piece' },
  { e: '🧸', n: 'teddy bear' },
  { e: '🪅', n: 'pinata' },
  { e: '🪩', n: 'mirror ball disco' },
  { e: '🪄', n: 'magic wand' },
  { e: '🔮', n: 'crystal ball' },
  { e: '🧿', n: 'nazar amulet' },
  { e: '🪬', n: 'hamsa' },
  { e: '🎼', n: 'musical score' },
  { e: '🎵', n: 'musical note' },
  { e: '🎶', n: 'musical notes' },
  { e: '🎤', n: 'microphone sing' },
  { e: '🎧', n: 'headphone music' },
  { e: '📻', n: 'radio' },
  { e: '🎷', n: 'saxophone' },
  { e: '🪗', n: 'accordion' },
  { e: '🎸', n: 'guitar' },
  { e: '🎹', n: 'musical keyboard piano' },
  { e: '🎺', n: 'trumpet' },
  { e: '🎻', n: 'violin' },
  { e: '🪕', n: 'banjo' },
  { e: '🥁', n: 'drum' },
  { e: '🪘', n: 'long drum' },
  { e: '📱', n: 'mobile phone' },
  { e: '📲', n: 'mobile phone arrow' },
  { e: '☎️', n: 'telephone' },
  { e: '📞', n: 'telephone receiver' },
  { e: '📟', n: 'pager' },
  { e: '📠', n: 'fax machine' },
  { e: '🔋', n: 'battery' },
  { e: '🔌', n: 'electric plug' },
  { e: '💻', n: 'laptop computer' },
  { e: '🖥️', n: 'desktop computer' },
  { e: '🖨️', n: 'printer' },
  { e: '⌨️', n: 'keyboard' },
  { e: '🖱️', n: 'computer mouse' },
  { e: '💽', n: 'computer disk' },
  { e: '💾', n: 'floppy disk' },
  { e: '💿', n: 'optical disk cd' },
  { e: '📀', n: 'dvd' },
  { e: '🎥', n: 'movie camera' },
  { e: '🎬', n: 'clapper board film' },
  { e: '📺', n: 'television tv' },
  { e: '📷', n: 'camera' },
  { e: '📸', n: 'camera flash' },
  { e: '📹', n: 'video camera' },
  { e: '📼', n: 'videocassette' },
  { e: '🔍', n: 'magnifying glass left search' },
  { e: '🔎', n: 'magnifying glass right search' },
  { e: '🕯️', n: 'candle' },
  { e: '💡', n: 'light bulb idea' },
  { e: '🔦', n: 'flashlight' },
  { e: '🏮', n: 'red paper lantern' },
  { e: '📔', n: 'notebook decorative cover' },
  { e: '📕', n: 'closed book' },
  { e: '📖', n: 'open book read' },
  { e: '📗', n: 'green book' },
  { e: '📘', n: 'blue book' },
  { e: '📙', n: 'orange book' },
  { e: '📚', n: 'books study' },
  { e: '📓', n: 'notebook' },
  { e: '📒', n: 'ledger' },
  { e: '📃', n: 'page with curl' },
  { e: '📜', n: 'scroll' },
  { e: '📄', n: 'page facing up' },
  { e: '📰', n: 'newspaper' },
  { e: '📑', n: 'bookmark tabs' },
  { e: '🔖', n: 'bookmark' },
  { e: '💰', n: 'money bag' },
  { e: '💴', n: 'yen banknote' },
  { e: '💵', n: 'dollar banknote money' },
  { e: '💶', n: 'euro banknote' },
  { e: '💷', n: 'pound banknote' },
  { e: '💸', n: 'money with wings' },
  { e: '💳', n: 'credit card' },
  { e: '🧾', n: 'receipt' },
  { e: '✉️', n: 'envelope email' },
  { e: '📧', n: 'e-mail' },
  { e: '📨', n: 'incoming envelope' },
  { e: '📩', n: 'envelope with arrow' },
  { e: '📤', n: 'outbox tray' },
  { e: '📥', n: 'inbox tray' },
  { e: '📦', n: 'package' },
  { e: '📫', n: 'closed mailbox raised' },
  { e: '📬', n: 'open mailbox raised' },
  { e: '📭', n: 'open mailbox lowered' },
  { e: '📮', n: 'postbox' },
  { e: '🗳️', n: 'ballot box' },
  { e: '✏️', n: 'pencil' },
  { e: '✒️', n: 'black nib' },
  { e: '🖋️', n: 'fountain pen' },
  { e: '🖊️', n: 'pen' },
  { e: '🖌️', n: 'paintbrush' },
  { e: '🖍️', n: 'crayon' },
  { e: '📝', n: 'memo note' },
  { e: '📁', n: 'file folder' },
  { e: '📂', n: 'open file folder' },
  { e: '📅', n: 'calendar' },
  { e: '📆', n: 'tear-off calendar' },
  { e: '🗒️', n: 'spiral notepad' },
  { e: '🗓️', n: 'spiral calendar' },
  { e: '📇', n: 'card index' },
  { e: '📈', n: 'chart increasing growth' },
  { e: '📉', n: 'chart decreasing' },
  { e: '📊', n: 'bar chart' },
  { e: '📋', n: 'clipboard' },
  { e: '📌', n: 'pushpin' },
  { e: '📍', n: 'round pushpin' },
  { e: '📎', n: 'paperclip' },
  { e: '🖇️', n: 'linked paperclips' },
  { e: '📏', n: 'straight ruler' },
  { e: '📐', n: 'triangular ruler' },
  { e: '✂️', n: 'scissors' },
  { e: '🗃️', n: 'card file box' },
  { e: '🗄️', n: 'file cabinet' },
  { e: '🗑️', n: 'wastebasket trash' },
  { e: '🔒', n: 'locked lock' },
  { e: '🔓', n: 'unlocked' },
  { e: '🔏', n: 'locked with pen' },
  { e: '🔐', n: 'locked with key' },
  { e: '🔑', n: 'key' },
  { e: '🗝️', n: 'old key' },
  { e: '🔨', n: 'hammer' },
  { e: '🪓', n: 'axe' },
  { e: '⛏️', n: 'pick' },
  { e: '⚒️', n: 'hammer and pick' },
  { e: '🛠️', n: 'hammer and wrench tools' },
  { e: '🗡️', n: 'dagger' },
  { e: '⚔️', n: 'crossed swords' },
  { e: '🔫', n: 'water pistol' },
  { e: '🪃', n: 'boomerang' },
  { e: '🏹', n: 'bow arrow' },
  { e: '🛡️', n: 'shield' },
  { e: '🔧', n: 'wrench' },
  { e: '🔩', n: 'nut and bolt' },
  { e: '⚙️', n: 'gear settings' },
  { e: '🗜️', n: 'clamp' },
  { e: '⚖️', n: 'balance scale' },
  { e: '🦯', n: 'white cane' },
  { e: '🔗', n: 'link' },
  { e: '⛓️', n: 'chains' },
  { e: '🪝', n: 'hook' },
  { e: '🧰', n: 'toolbox' },
  { e: '🧲', n: 'magnet' },
  { e: '🪜', n: 'ladder' },
  { e: '⚗️', n: 'alembic science' },
  { e: '🧪', n: 'test tube science' },
  { e: '🧫', n: 'petri dish' },
  { e: '🧬', n: 'dna' },
  { e: '🔬', n: 'microscope' },
  { e: '🔭', n: 'telescope' },
  { e: '📡', n: 'satellite antenna' },
  { e: '💉', n: 'syringe' },
  { e: '🩸', n: 'drop of blood' },
  { e: '💊', n: 'pill medicine' },
  { e: '🩹', n: 'adhesive bandage' },
  { e: '🩺', n: 'stethoscope' },
  { e: '🚪', n: 'door' },
  { e: '🛏️', n: 'bed' },
  { e: '🛋️', n: 'couch and lamp' },
  { e: '🪑', n: 'chair' },
  { e: '🚽', n: 'toilet' },
  { e: '🚿', n: 'shower' },
  { e: '🛁', n: 'bathtub' },
  { e: '🪒', n: 'razor' },
  { e: '🧴', n: 'lotion bottle' },
  { e: '🧷', n: 'safety pin' },
  { e: '🧹', n: 'broom' },
  { e: '🧺', n: 'basket' },
  { e: '🧻', n: 'roll of paper' },
  { e: '🪣', n: 'bucket' },
  { e: '🧼', n: 'soap' },
  { e: '🪥', n: 'toothbrush' },
  { e: '🧽', n: 'sponge' },
  { e: '🧯', n: 'fire extinguisher' },
  { e: '🛒', n: 'shopping cart' },
  { e: '🚬', n: 'cigarette' },
  { e: '⚰️', n: 'coffin' },
  { e: '🪦', n: 'headstone' },
  { e: '⚱️', n: 'funeral urn' },
  { e: '🗿', n: 'moai' },
  { e: '🪧', n: 'placard' },
  { e: '🏧', n: 'atm sign' },
  { e: '🚮', n: 'litter in bin' },
  { e: '🚰', n: 'potable water' },
  { e: '♿', n: 'wheelchair symbol' },
  { e: '🚹', n: 'mens room' },
  { e: '🚺', n: 'womens room' },
  { e: '🚻', n: 'restroom' },
  { e: '🚼', n: 'baby symbol' },
  { e: '🚾', n: 'water closet wc' },
  { e: '🛂', n: 'passport control' },
  { e: '🛃', n: 'customs' },
  { e: '🛄', n: 'baggage claim' },
  { e: '🛅', n: 'left luggage' },
  { e: '⚠️', n: 'warning' },
  { e: '🚸', n: 'children crossing' },
  { e: '⛔', n: 'no entry' },
  { e: '🚫', n: 'prohibited' },
  { e: '🚳', n: 'no bicycles' },
  { e: '🚭', n: 'no smoking' },
  { e: '🚯', n: 'no littering' },
  { e: '🚱', n: 'non-potable water' },
  { e: '🚷', n: 'no pedestrians' },
  { e: '📵', n: 'no mobile phones' },
  { e: '🔞', n: 'no one under eighteen' },
  { e: '☢️', n: 'radioactive' },
  { e: '☣️', n: 'biohazard' },
  { e: '⬆️', n: 'up arrow' },
  { e: '↗️', n: 'up-right arrow' },
  { e: '➡️', n: 'right arrow' },
  { e: '↘️', n: 'down-right arrow' },
  { e: '⬇️', n: 'down arrow' },
  { e: '↙️', n: 'down-left arrow' },
  { e: '⬅️', n: 'left arrow' },
  { e: '↖️', n: 'up-left arrow' },
  { e: '↕️', n: 'up-down arrow' },
  { e: '↔️', n: 'left-right arrow' },
  { e: '↩️', n: 'right arrow curving left' },
  { e: '↪️', n: 'left arrow curving right' },
  { e: '⤴️', n: 'right arrow curving up' },
  { e: '⤵️', n: 'right arrow curving down' },
  { e: '🔃', n: 'clockwise vertical arrows' },
  { e: '🔄', n: 'counterclockwise arrows button refresh' },
  { e: '🔙', n: 'back arrow' },
  { e: '🔚', n: 'end arrow' },
  { e: '🔛', n: 'on arrow' },
  { e: '🔜', n: 'soon arrow' },
  { e: '🔝', n: 'top arrow' },
  { e: '🛐', n: 'place of worship' },
  { e: '⚛️', n: 'atom symbol' },
  { e: '🕉️', n: 'om' },
  { e: '✡️', n: 'star of david' },
  { e: '☸️', n: 'wheel of dharma' },
  { e: '☯️', n: 'yin yang' },
  { e: '✝️', n: 'latin cross' },
  { e: '☦️', n: 'orthodox cross' },
  { e: '☪️', n: 'star and crescent' },
  { e: '☮️', n: 'peace symbol' },
  { e: '🕎', n: 'menorah' },
  { e: '🔯', n: 'dotted six-pointed star' },
  { e: '♈', n: 'aries' },
  { e: '♉', n: 'taurus' },
  { e: '♊', n: 'gemini' },
  { e: '♋', n: 'cancer' },
  { e: '♌', n: 'leo' },
  { e: '♍', n: 'virgo' },
  { e: '♎', n: 'libra' },
  { e: '♏', n: 'scorpio' },
  { e: '♐', n: 'sagittarius' },
  { e: '♑', n: 'capricorn' },
  { e: '♒', n: 'aquarius' },
  { e: '♓', n: 'pisces' },
  { e: '⛎', n: 'ophiuchus' },
  { e: '🔀', n: 'shuffle tracks button' },
  { e: '🔁', n: 'repeat button' },
  { e: '🔂', n: 'repeat single button' },
  { e: '▶️', n: 'play button' },
  { e: '⏩', n: 'fast-forward button' },
  { e: '⏭️', n: 'next track button' },
  { e: '⏯️', n: 'play or pause button' },
  { e: '◀️', n: 'reverse button' },
  { e: '⏪', n: 'fast reverse button' },
  { e: '⏮️', n: 'last track button' },
  { e: '🔼', n: 'upwards button' },
  { e: '⏫', n: 'fast up button' },
  { e: '🔽', n: 'downwards button' },
  { e: '⏬', n: 'fast down button' },
  { e: '⏸️', n: 'pause button' },
  { e: '⏹️', n: 'stop button' },
  { e: '⏺️', n: 'record button' },
  { e: '⏏️', n: 'eject button' },
  { e: '🎦', n: 'cinema' },
  { e: '🔅', n: 'dim button' },
  { e: '🔆', n: 'bright button' },
  { e: '📶', n: 'antenna bars signal' },
  { e: '📳', n: 'vibration mode' },
  { e: '📴', n: 'mobile phone off' },
  { e: '♀️', n: 'female sign' },
  { e: '♂️', n: 'male sign' },
  { e: '⚧️', n: 'transgender symbol' },
  { e: '✖️', n: 'multiply' },
  { e: '➕', n: 'plus' },
  { e: '➖', n: 'minus' },
  { e: '➗', n: 'divide' },
  { e: '♾️', n: 'infinity' },
  { e: '‼️', n: 'double exclamation mark' },
  { e: '⁉️', n: 'exclamation question mark' },
  { e: '❓', n: 'question mark' },
  { e: '❔', n: 'white question mark' },
  { e: '❕', n: 'white exclamation mark' },
  { e: '❗', n: 'exclamation mark' },
  { e: '〰️', n: 'wavy dash' },
  { e: '💱', n: 'currency exchange' },
  { e: '💲', n: 'heavy dollar sign' },
  { e: '⚕️', n: 'medical symbol' },
  { e: '♻️', n: 'recycling symbol' },
  { e: '⚜️', n: 'fleur-de-lis' },
  { e: '🔱', n: 'trident emblem' },
  { e: '📛', n: 'name badge' },
  { e: '🔰', n: 'japanese symbol for beginner' },
  { e: '⭕', n: 'hollow red circle' },
  { e: '✅', n: 'check mark button yes done' },
  { e: '☑️', n: 'check box with check' },
  { e: '✔️', n: 'check mark' },
  { e: '❌', n: 'cross mark no' },
  { e: '❎', n: 'cross mark button' },
  { e: '➰', n: 'curly loop' },
  { e: '➿', n: 'double curly loop' },
  { e: '〽️', n: 'part alternation mark' },
  { e: '✳️', n: 'eight-spoked asterisk' },
  { e: '✴️', n: 'eight-pointed star' },
  { e: '❇️', n: 'sparkle' },
  { e: '©️', n: 'copyright' },
  { e: '®️', n: 'registered' },
  { e: '™️', n: 'trade mark' },
  { e: '#️⃣', n: 'keycap number sign hash' },
  { e: '*️⃣', n: 'keycap asterisk' },
  { e: '0️⃣', n: 'keycap 0' },
  { e: '1️⃣', n: 'keycap 1' },
  { e: '2️⃣', n: 'keycap 2' },
  { e: '3️⃣', n: 'keycap 3' },
  { e: '4️⃣', n: 'keycap 4' },
  { e: '5️⃣', n: 'keycap 5' },
  { e: '6️⃣', n: 'keycap 6' },
  { e: '7️⃣', n: 'keycap 7' },
  { e: '8️⃣', n: 'keycap 8' },
  { e: '9️⃣', n: 'keycap 9' },
  { e: '🔟', n: 'keycap 10' },
  { e: '🔠', n: 'input latin uppercase' },
  { e: '🔡', n: 'input latin lowercase' },
  { e: '🔢', n: 'input numbers' },
  { e: '🔣', n: 'input symbols' },
  { e: '🔤', n: 'input latin letters' },
  { e: '🅰️', n: 'a button blood type' },
  { e: '🆎', n: 'ab button blood type' },
  { e: '🅱️', n: 'b button blood type' },
  { e: '🆑', n: 'cl button' },
  { e: '🆒', n: 'cool button' },
  { e: '🆓', n: 'free button' },
  { e: 'ℹ️', n: 'information' },
  { e: '🆔', n: 'id button' },
  { e: 'Ⓜ️', n: 'circled m' },
  { e: '🆕', n: 'new button' },
  { e: '🆖', n: 'ng button' },
  { e: '🅾️', n: 'o button blood type' },
  { e: '🆗', n: 'ok button' },
  { e: '🅿️', n: 'p button parking' },
  { e: '🆘', n: 'sos button help' },
  { e: '🆙', n: 'up button' },
  { e: '🆚', n: 'vs button' },
  { e: '🈁', n: 'japanese here button' },
  { e: '🈂️', n: 'japanese service charge button' },
  { e: '🈷️', n: 'japanese monthly amount button' },
  { e: '🈶', n: 'japanese not free of charge button' },
  { e: '🈯', n: 'japanese reserved button' },
  { e: '🉐', n: 'japanese bargain button' },
  { e: '🈹', n: 'japanese discount button' },
  { e: '🈚', n: 'japanese free of charge button' },
  { e: '🈲', n: 'japanese prohibited button' },
  { e: '🉑', n: 'japanese acceptable button' },
  { e: '🈸', n: 'japanese application button' },
  { e: '🈴', n: 'japanese passing grade button' },
  { e: '🈳', n: 'japanese vacancy button' },
  { e: '㊗️', n: 'japanese congratulations button' },
  { e: '㊙️', n: 'japanese secret button' },
  { e: '🈺', n: 'japanese open for business button' },
  { e: '🈵', n: 'japanese no vacancy button' },
  { e: '🔴', n: 'red circle' },
  { e: '🟠', n: 'orange circle' },
  { e: '🟡', n: 'yellow circle' },
  { e: '🟢', n: 'green circle' },
  { e: '🔵', n: 'blue circle' },
  { e: '🟣', n: 'purple circle' },
  { e: '🟤', n: 'brown circle' },
  { e: '⚫', n: 'black circle' },
  { e: '⚪', n: 'white circle' },
  { e: '🟥', n: 'red square' },
  { e: '🟧', n: 'orange square' },
  { e: '🟨', n: 'yellow square' },
  { e: '🟩', n: 'green square' },
  { e: '🟦', n: 'blue square' },
  { e: '🟪', n: 'purple square' },
  { e: '🟫', n: 'brown square' },
  { e: '⬛', n: 'black large square' },
  { e: '⬜', n: 'white large square' },
  { e: '◼️', n: 'black medium square' },
  { e: '◻️', n: 'white medium square' },
  { e: '◾', n: 'black medium-small square' },
  { e: '◽', n: 'white medium-small square' },
  { e: '▪️', n: 'black small square' },
  { e: '▫️', n: 'white small square' },
  { e: '🔶', n: 'large orange diamond' },
  { e: '🔷', n: 'large blue diamond' },
  { e: '🔸', n: 'small orange diamond' },
  { e: '🔹', n: 'small blue diamond' },
  { e: '🔺', n: 'red triangle pointed up' },
  { e: '🔻', n: 'red triangle pointed down' },
  { e: '💠', n: 'diamond with a dot' },
  { e: '🔘', n: 'radio button' },
  { e: '🔳', n: 'white square button' },
  { e: '🔲', n: 'black square button' },
  { e: '🏁', n: 'chequered flag finish' },
  { e: '🚩', n: 'triangular flag' },
  { e: '🎌', n: 'crossed flags' },
  { e: '🏴', n: 'black flag' },
  { e: '🏳️', n: 'white flag' },
  { e: '🏳️‍🌈', n: 'rainbow flag pride' },
  { e: '🏳️‍⚧️', n: 'transgender flag' },
  { e: '🏴‍☠️', n: 'pirate flag' },
  { e: '🔥', n: 'fire lit hot' },
  { e: '✨', n: 'sparkles shiny' },
  { e: '🌟', n: 'glowing star' },
  { e: '⭐', n: 'star' },
  { e: '💫', n: 'dizzy' },
  { e: '⚡', n: 'high voltage lightning' },
  { e: '☀️', n: 'sun sunny' },
  { e: '🌤️', n: 'sun behind small cloud' },
  { e: '⛅', n: 'sun behind cloud' },
  { e: '🌥️', n: 'sun behind large cloud' },
  { e: '☁️', n: 'cloud' },
  { e: '🌧️', n: 'cloud with rain' },
  { e: '⛈️', n: 'cloud with lightning and rain' },
  { e: '🌩️', n: 'cloud with lightning' },
  { e: '🌨️', n: 'cloud with snow' },
  { e: '❄️', n: 'snowflake cold' },
  { e: '☃️', n: 'snowman' },
  { e: '⛄', n: 'snowman without snow' },
  { e: '🌬️', n: 'wind face' },
  { e: '💨', n: 'dashing away' },
  { e: '🌪️', n: 'tornado' },
  { e: '🌫️', n: 'fog' },
  { e: '🌈', n: 'rainbow' },
  { e: '☂️', n: 'umbrella' },
  { e: '☔', n: 'umbrella with rain drops' },
  { e: '💧', n: 'droplet water' },
  { e: '💦', n: 'sweat droplets' },
  { e: '🌊', n: 'water wave ocean' },
  { e: '🍏', n: 'green apple' },
  { e: '🍎', n: 'red apple' },
  { e: '🍐', n: 'pear' },
  { e: '🍊', n: 'tangerine orange' },
  { e: '🍋', n: 'lemon' },
  { e: '🍌', n: 'banana' },
  { e: '🍉', n: 'watermelon' },
  { e: '🍇', n: 'grapes' },
  { e: '🍓', n: 'strawberry' },
  { e: '🫐', n: 'blueberries' },
  { e: '🍈', n: 'melon' },
  { e: '🍒', n: 'cherries' },
  { e: '🍑', n: 'peach' },
  { e: '🥭', n: 'mango' },
  { e: '🍍', n: 'pineapple' },
  { e: '🥥', n: 'coconut' },
  { e: '🥝', n: 'kiwi fruit' },
  { e: '🍅', n: 'tomato' },
  { e: '🍆', n: 'eggplant' },
  { e: '🥑', n: 'avocado' },
  { e: '🥦', n: 'broccoli' },
  { e: '🥬', n: 'leafy green' },
  { e: '🥒', n: 'cucumber' },
  { e: '🌶️', n: 'hot pepper spicy' },
  { e: '🫑', n: 'bell pepper' },
  { e: '🌽', n: 'ear of corn' },
  { e: '🥕', n: 'carrot' },
  { e: '🫒', n: 'olive' },
  { e: '🧄', n: 'garlic' },
  { e: '🧅', n: 'onion' },
  { e: '🥔', n: 'potato' },
  { e: '🍠', n: 'roasted sweet potato' },
  { e: '🥐', n: 'croissant' },
  { e: '🥯', n: 'bagel' },
  { e: '🍞', n: 'bread' },
  { e: '🥖', n: 'baguette bread' },
  { e: '🫓', n: 'flatbread' },
  { e: '🥨', n: 'pretzel' },
  { e: '🧀', n: 'cheese wedge' },
  { e: '🥚', n: 'egg' },
  { e: '🍳', n: 'cooking fried egg' },
  { e: '🧈', n: 'butter' },
  { e: '🥞', n: 'pancakes' },
  { e: '🧇', n: 'waffle' },
  { e: '🥓', n: 'bacon' },
  { e: '🥩', n: 'cut of meat' },
  { e: '🍗', n: 'poultry leg' },
  { e: '🍖', n: 'meat on bone' },
  { e: '🦴', n: 'bone' },
  { e: '🌭', n: 'hot dog' },
  { e: '🍔', n: 'hamburger burger' },
  { e: '🍟', n: 'french fries' },
  { e: '🍕', n: 'pizza' },
  { e: '🫓', n: 'flatbread' },
  { e: '🥪', n: 'sandwich' },
  { e: '🥙', n: 'stuffed flatbread' },
  { e: '🧆', n: 'falafel' },
  { e: '🌮', n: 'taco' },
  { e: '🌯', n: 'burrito' },
  { e: '🫔', n: 'tamale' },
  { e: '🥗', n: 'green salad' },
  { e: '🥘', n: 'shallow pan of food' },
  { e: '🫕', n: 'fondue' },
  { e: '🥫', n: 'canned food' },
  { e: '🍝', n: 'spaghetti pasta' },
  { e: '🍜', n: 'steaming bowl ramen' },
  { e: '🍲', n: 'pot of food' },
  { e: '🍛', n: 'curry rice' },
  { e: '🍣', n: 'sushi' },
  { e: '🍱', n: 'bento box' },
  { e: '🥟', n: 'dumpling' },
  { e: '🦪', n: 'oyster' },
  { e: '🍤', n: 'fried shrimp' },
  { e: '🍙', n: 'rice ball' },
  { e: '🍚', n: 'cooked rice' },
  { e: '🍘', n: 'rice cracker' },
  { e: '🍥', n: 'fish cake with swirl' },
  { e: '🥠', n: 'fortune cookie' },
  { e: '🥮', n: 'moon cake' },
  { e: '🍢', n: 'oden' },
  { e: '🍡', n: 'dango' },
  { e: '🍧', n: 'shaved ice' },
  { e: '🍨', n: 'ice cream' },
  { e: '🍦', n: 'soft ice cream' },
  { e: '🥧', n: 'pie' },
  { e: '🧁', n: 'cupcake' },
  { e: '🍰', n: 'shortcake cake' },
  { e: '🎂', n: 'birthday cake' },
  { e: '🍮', n: 'custard' },
  { e: '🍭', n: 'lollipop' },
  { e: '🍬', n: 'candy' },
  { e: '🍫', n: 'chocolate bar' },
  { e: '🍿', n: 'popcorn' },
  { e: '🍩', n: 'doughnut donut' },
  { e: '🍪', n: 'cookie' },
  { e: '🌰', n: 'chestnut' },
  { e: '🥜', n: 'peanuts' },
  { e: '🍯', n: 'honey pot' },
  { e: '🥛', n: 'glass of milk' },
  { e: '🍼', n: 'baby bottle' },
  { e: '☕', n: 'hot beverage coffee tea' },
  { e: '🫖', n: 'teapot' },
  { e: '🍵', n: 'teacup without handle' },
  { e: '🧃', n: 'beverage box' },
  { e: '🥤', n: 'cup with straw' },
  { e: '🧋', n: 'bubble tea' },
  { e: '🍶', n: 'sake' },
  { e: '🍺', n: 'beer mug' },
  { e: '🍻', n: 'clinking beer mugs cheers' },
  { e: '🥂', n: 'clinking glasses cheers' },
  { e: '🍷', n: 'wine glass' },
  { e: '🥃', n: 'tumbler glass' },
  { e: '🍸', n: 'cocktail glass' },
  { e: '🍹', n: 'tropical drink' },
  { e: '🧉', n: 'mate' },
  { e: '🍾', n: 'bottle with popping cork champagne' },
  { e: '🧊', n: 'ice' },
  { e: '🥄', n: 'spoon' },
  { e: '🍴', n: 'fork and knife' },
  { e: '🍽️', n: 'fork and knife with plate' },
  { e: '🥣', n: 'bowl with spoon' },
  { e: '🥡', n: 'takeout box' },
  { e: '🥢', n: 'chopsticks' },
  { e: '🧂', n: 'salt' },
  { e: '🐶', n: 'dog face puppy' },
  { e: '🐱', n: 'cat face kitty' },
  { e: '🐭', n: 'mouse face' },
  { e: '🐹', n: 'hamster' },
  { e: '🐰', n: 'rabbit face bunny' },
  { e: '🦊', n: 'fox' },
  { e: '🐻', n: 'bear' },
  { e: '🐼', n: 'panda' },
  { e: '🐻‍❄️', n: 'polar bear' },
  { e: '🐨', n: 'koala' },
  { e: '🐯', n: 'tiger face' },
  { e: '🦁', n: 'lion' },
  { e: '🐮', n: 'cow face' },
  { e: '🐷', n: 'pig face' },
  { e: '🐸', n: 'frog' },
  { e: '🐵', n: 'monkey face' },
  { e: '🙈', n: 'see-no-evil monkey' },
  { e: '🦄', n: 'unicorn' },
  { e: '🐝', n: 'honeybee bee' },
  { e: '🐛', n: 'bug' },
  { e: '🦋', n: 'butterfly' },
  { e: '🐌', n: 'snail' },
  { e: '🐞', n: 'lady beetle' },
  { e: '🐜', n: 'ant' },
  { e: '🪰', n: 'fly' },
  { e: '🪱', n: 'worm' },
  { e: '🐢', n: 'turtle' },
  { e: '🐍', n: 'snake' },
  { e: '🦎', n: 'lizard' },
  { e: '🦖', n: 't-rex dinosaur' },
  { e: '🦕', n: 'sauropod dinosaur' },
  { e: '🐙', n: 'octopus' },
  { e: '🦑', n: 'squid' },
  { e: '🦐', n: 'shrimp' },
  { e: '🦞', n: 'lobster' },
  { e: '🦀', n: 'crab' },
  { e: '🐡', n: 'blowfish' },
  { e: '🐠', n: 'tropical fish' },
  { e: '🐟', n: 'fish' },
  { e: '🐬', n: 'dolphin' },
  { e: '🐳', n: 'spouting whale' },
  { e: '🐋', n: 'whale' },
  { e: '🦈', n: 'shark' },
  { e: '🐊', n: 'crocodile' },
  { e: '🐅', n: 'tiger' },
  { e: '🐆', n: 'leopard' },
  { e: '🦓', n: 'zebra' },
  { e: '🦍', n: 'gorilla' },
  { e: '🦧', n: 'orangutan' },
  { e: '🐘', n: 'elephant' },
  { e: '🦣', n: 'mammoth' },
  { e: '🦏', n: 'rhinoceros' },
  { e: '🦛', n: 'hippopotamus' },
  { e: '🐪', n: 'camel' },
  { e: '🐫', n: 'two-hump camel' },
  { e: '🦒', n: 'giraffe' },
  { e: '🦘', n: 'kangaroo' },
  { e: '🦬', n: 'bison' },
  { e: '🐃', n: 'water buffalo' },
  { e: '🐂', n: 'ox' },
  { e: '🐄', n: 'cow' },
  { e: '🐎', n: 'horse' },
  { e: '🐖', n: 'pig' },
  { e: '🐏', n: 'ram' },
  { e: '🐑', n: 'ewe sheep' },
  { e: '🦙', n: 'llama' },
  { e: '🐐', n: 'goat' },
  { e: '🦌', n: 'deer' },
  { e: '🐕', n: 'dog' },
  { e: '🐩', n: 'poodle' },
  { e: '🦮', n: 'guide dog' },
  { e: '🐕‍🦺', n: 'service dog' },
  { e: '🐈', n: 'cat' },
  { e: '🐈‍⬛', n: 'black cat' },
  { e: '🪶', n: 'feather' },
  { e: '🐓', n: 'rooster' },
  { e: '🦃', n: 'turkey' },
  { e: '🦤', n: 'dodo' },
  { e: '🦚', n: 'peacock' },
  { e: '🦜', n: 'parrot' },
  { e: '🦢', n: 'swan' },
  { e: '🦩', n: 'flamingo' },
  { e: '🕊️', n: 'dove' },
  { e: '🐇', n: 'rabbit' },
  { e: '🦝', n: 'raccoon' },
  { e: '🦨', n: 'skunk' },
  { e: '🦡', n: 'badger' },
  { e: '🦫', n: 'beaver' },
  { e: '🦦', n: 'otter' },
  { e: '🦥', n: 'sloth' },
  { e: '🐁', n: 'mouse' },
  { e: '🐀', n: 'rat' },
  { e: '🐿️', n: 'chipmunk' },
  { e: '🦔', n: 'hedgehog' },
  { e: '🐾', n: 'paw prints' },
  { e: '🐉', n: 'dragon' },
  { e: '🐲', n: 'dragon face' },
  { e: '🌵', n: 'cactus' },
  { e: '🎄', n: 'christmas tree' },
  { e: '🌲', n: 'evergreen tree' },
  { e: '🌳', n: 'deciduous tree' },
  { e: '🌴', n: 'palm tree' },
  { e: '🪵', n: 'wood' },
  { e: '🌱', n: 'seedling' },
  { e: '🌿', n: 'herb' },
  { e: '☘️', n: 'shamrock' },
  { e: '🍀', n: 'four leaf clover luck' },
  { e: '🎍', n: 'pine decoration' },
  { e: '🪴', n: 'potted plant' },
  { e: '🎋', n: 'tanabata tree' },
  { e: '🍃', n: 'leaf fluttering in wind' },
  { e: '🍂', n: 'fallen leaf' },
  { e: '🍁', n: 'maple leaf' },
  { e: '🍄', n: 'mushroom' },
  { e: '🐚', n: 'spiral shell' },
  { e: '🪨', n: 'rock' },
  { e: '🌾', n: 'sheaf of rice' },
  { e: '💐', n: 'bouquet flowers' },
  { e: '🌷', n: 'tulip' },
  { e: '🌹', n: 'rose' },
  { e: '🥀', n: 'wilted flower' },
  { e: '🌺', n: 'hibiscus' },
  { e: '🌸', n: 'cherry blossom' },
  { e: '🌼', n: 'blossom' },
  { e: '🌻', n: 'sunflower' },
  { e: '🌞', n: 'sun with face' },
  { e: '🌝', n: 'full moon face' },
  { e: '🌛', n: 'first quarter moon face' },
  { e: '🌜', n: 'last quarter moon face' },
  { e: '🌚', n: 'new moon face' },
  { e: '🌕', n: 'full moon' },
  { e: '🌖', n: 'waning gibbous moon' },
  { e: '🌗', n: 'last quarter moon' },
  { e: '🌘', n: 'waning crescent moon' },
  { e: '🌑', n: 'new moon' },
  { e: '🌒', n: 'waxing crescent moon' },
  { e: '🌓', n: 'first quarter moon' },
  { e: '🌔', n: 'waxing gibbous moon' },
  { e: '🌙', n: 'crescent moon' },
  { e: '🌎', n: 'globe americas earth' },
  { e: '🌍', n: 'globe europe africa' },
  { e: '🌏', n: 'globe asia australia' },
  { e: '🪐', n: 'ringed planet saturn' },
  { e: '💫', n: 'dizzy' },
  { e: '⭐', n: 'star' },
  { e: '🌟', n: 'glowing star' },
  { e: '✨', n: 'sparkles' },
  { e: '⚡', n: 'lightning' },
  { e: '☄️', n: 'comet' },
  { e: '💥', n: 'collision' },
  { e: '🔥', n: 'fire' },
  { e: '🌪️', n: 'tornado' },
  { e: '🌈', n: 'rainbow' },
  { e: '☀️', n: 'sun' },
  { e: '🌤️', n: 'partly sunny' },
  { e: '⛅', n: 'partly cloudy' },
  { e: '☁️', n: 'cloud' },
  { e: '🌧️', n: 'rain' },
  { e: '⛈️', n: 'thunderstorm' },
  { e: '🌩️', n: 'lightning cloud' },
  { e: '🌨️', n: 'snow' },
  { e: '❄️', n: 'snowflake' },
  { e: '☃️', n: 'snowman' },
  { e: '💨', n: 'wind' },
  { e: '💧', n: 'droplet' },
  { e: '💦', n: 'sweat' },
  { e: '☔', n: 'umbrella rain' },
  { e: '🌊', n: 'wave' },
  { e: '🚗', n: 'automobile car' },
  { e: '🚕', n: 'taxi' },
  { e: '🚙', n: 'sport utility vehicle' },
  { e: '🚌', n: 'bus' },
  { e: '🚎', n: 'trolleybus' },
  { e: '🏎️', n: 'racing car' },
  { e: '🚓', n: 'police car' },
  { e: '🚑', n: 'ambulance' },
  { e: '🚒', n: 'fire engine' },
  { e: '🚐', n: 'minibus' },
  { e: '🛻', n: 'pickup truck' },
  { e: '🚚', n: 'delivery truck' },
  { e: '🚛', n: 'articulated lorry' },
  { e: '🚜', n: 'tractor' },
  { e: '🦯', n: 'white cane' },
  { e: '🦽', n: 'manual wheelchair' },
  { e: '🦼', n: 'motorized wheelchair' },
  { e: '🛴', n: 'kick scooter' },
  { e: '🚲', n: 'bicycle bike' },
  { e: '🛵', n: 'motor scooter' },
  { e: '🏍️', n: 'motorcycle' },
  { e: '🛺', n: 'auto rickshaw' },
  { e: '🚨', n: 'police car light' },
  { e: '🚔', n: 'oncoming police car' },
  { e: '🚍', n: 'oncoming bus' },
  { e: '🚘', n: 'oncoming automobile' },
  { e: '🚖', n: 'oncoming taxi' },
  { e: '🚡', n: 'aerial tramway' },
  { e: '🚠', n: 'mountain cableway' },
  { e: '🚟', n: 'suspension railway' },
  { e: '🚃', n: 'railway car' },
  { e: '🚋', n: 'tram car' },
  { e: '🚞', n: 'mountain railway' },
  { e: '🚝', n: 'monorail' },
  { e: '🚄', n: 'high-speed train' },
  { e: '🚅', n: 'bullet train' },
  { e: '🚈', n: 'light rail' },
  { e: '🚂', n: 'locomotive' },
  { e: '🚆', n: 'train' },
  { e: '🚇', n: 'metro' },
  { e: '🚊', n: 'tram' },
  { e: '🚉', n: 'station' },
  { e: '✈️', n: 'airplane plane flight' },
  { e: '🛫', n: 'airplane departure' },
  { e: '🛬', n: 'airplane arrival' },
  { e: '🛩️', n: 'small airplane' },
  { e: '💺', n: 'seat' },
  { e: '🛰️', n: 'satellite' },
  { e: '🚀', n: 'rocket launch' },
  { e: '🛸', n: 'flying saucer ufo' },
  { e: '🚁', n: 'helicopter' },
  { e: '🛶', n: 'canoe' },
  { e: '⛵', n: 'sailboat' },
  { e: '🚤', n: 'speedboat' },
  { e: '🛥️', n: 'motor boat' },
  { e: '🛳️', n: 'passenger ship' },
  { e: '⛴️', n: 'ferry' },
  { e: '🚢', n: 'ship' },
  { e: '⚓', n: 'anchor' },
  { e: '🪝', n: 'hook' },
  { e: '⛽', n: 'fuel pump' },
  { e: '🚧', n: 'construction' },
  { e: '🚦', n: 'vertical traffic light' },
  { e: '🚥', n: 'horizontal traffic light' },
  { e: '🚏', n: 'bus stop' },
  { e: '🗺️', n: 'world map' },
  { e: '🗿', n: 'moai' },
  { e: '🗽', n: 'statue of liberty' },
  { e: '🗼', n: 'tokyo tower' },
  { e: '🏰', n: 'castle' },
  { e: '🏯', n: 'japanese castle' },
  { e: '🏟️', n: 'stadium' },
  { e: '🎡', n: 'ferris wheel' },
  { e: '🎢', n: 'roller coaster' },
  { e: '🎠', n: 'carousel horse' },
  { e: '⛲', n: 'fountain' },
  { e: '⛱️', n: 'umbrella on ground' },
  { e: '🏖️', n: 'beach with umbrella' },
  { e: '🏝️', n: 'desert island' },
  { e: '🏜️', n: 'desert' },
  { e: '🌋', n: 'volcano' },
  { e: '⛰️', n: 'mountain' },
  { e: '🏔️', n: 'snow-capped mountain' },
  { e: '🗻', n: 'mount fuji' },
  { e: '🏕️', n: 'camping' },
  { e: '⛺', n: 'tent' },
  { e: '🏠', n: 'house' },
  { e: '🏡', n: 'house with garden' },
  { e: '🏘️', n: 'houses' },
  { e: '🏚️', n: 'derelict house' },
  { e: '🏗️', n: 'building construction' },
  { e: '🏭', n: 'factory' },
  { e: '🏢', n: 'office building' },
  { e: '🏬', n: 'department store' },
  { e: '🏣', n: 'japanese post office' },
  { e: '🏤', n: 'post office' },
  { e: '🏥', n: 'hospital' },
  { e: '🏦', n: 'bank' },
  { e: '🏨', n: 'hotel' },
  { e: '🏪', n: 'convenience store' },
  { e: '🏫', n: 'school' },
  { e: '🏩', n: 'love hotel' },
  { e: '💒', n: 'wedding' },
  { e: '🏛️', n: 'classical building' },
  { e: '⛪', n: 'church' },
  { e: '🕌', n: 'mosque' },
  { e: '🕍', n: 'synagogue' },
  { e: '🛕', n: 'hindu temple' },
  { e: '🕋', n: 'kaaba' },
  { e: '⛩️', n: 'shinto shrine' },
  { e: '🛤️', n: 'railway track' },
  { e: '🛣️', n: 'motorway' },
  { e: '🗾', n: 'map of japan' },
  { e: '🎑', n: 'moon viewing ceremony' },
  { e: '🏞️', n: 'national park' },
  { e: '🌅', n: 'sunrise' },
  { e: '🌄', n: 'sunrise over mountains' },
  { e: '🌠', n: 'shooting star' },
  { e: '🎇', n: 'sparkler' },
  { e: '🎆', n: 'fireworks' },
  { e: '🌇', n: 'sunset' },
  { e: '🌆', n: 'cityscape at dusk' },
  { e: '🏙️', n: 'cityscape' },
  { e: '🌃', n: 'night with stars' },
  { e: '🌌', n: 'milky way' },
  { e: '🌉', n: 'bridge at night' },
  { e: '🌁', n: 'foggy' },
]

const seen = new Set()
export const UNIQUE_EMOJIS = EMOJI_LIST.filter((item) => {
  if (seen.has(item.e)) return false
  seen.add(item.e)
  return true
})

export function searchEmojis(query = '') {
  const q = String(query || '')
    .trim()
    .toLowerCase()
  if (!q) return UNIQUE_EMOJIS
  return UNIQUE_EMOJIS.filter((item) => item.n.includes(q) || item.e.includes(q))
}
