/**
 * Real scholarship programs with eligibility tied to country/region.
 * URLs point at official sources — verify deadlines on the program site each cycle.
 */

export const SCHOLARSHIP_PROGRAMS = [
  {
    id: 'chevening',
    title: 'Chevening Scholarships',
    source: 'Chevening (UK FCDO)',
    url: 'https://www.chevening.org/scholarships/',
    focus: 'Fully funded one-year UK master’s for future leaders',
    fields: ['any'],
    regions: ['commonwealth', 'africa', 'global'],
    countries: ['*'], // eligible list is large; Chevening covers Botswana and most Commonwealth
    level: 'Master’s',
    funding: 'Fully funded',
    deadlineLabel: 'Usually November — check this year’s dates',
  },
  {
    id: 'commonwealth_shared',
    title: 'Commonwealth Shared Scholarships',
    source: 'CSC UK',
    url: 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships/',
    focus: 'UK master’s for candidates from least developed / lower-middle income Commonwealth countries',
    fields: ['any'],
    regions: ['commonwealth', 'africa'],
    countries: [
      'botswana',
      'namibia',
      'zambia',
      'zimbabwe',
      'malawi',
      'lesotho',
      'eswatini',
      'ghana',
      'kenya',
      'nigeria',
      'uganda',
      'tanzania',
      'rwanda',
    ],
    level: 'Master’s',
    funding: 'Fully funded',
    deadlineLabel: 'See this year’s CSC dates',
  },
  {
    id: 'mastercard',
    title: 'Mastercard Foundation Scholars Program',
    source: 'Mastercard Foundation',
    url: 'https://mastercardfdn.org/en/scholarships/',
    focus: 'Higher education pathways for young people from Africa',
    fields: ['any'],
    regions: ['africa', 'southern africa'],
    countries: ['*africa'],
    level: 'Undergrad · Master’s',
    funding: 'Fully / substantially funded',
    deadlineLabel: 'Dates depend on the partner university',
  },
  {
    id: 'daad',
    title: 'DAAD Scholarship Database',
    source: 'DAAD',
    url: 'https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/',
    focus: 'German-funded study and research awards across disciplines',
    fields: ['engineering', 'science', 'computer', 'business', 'any'],
    regions: ['global', 'africa', 'europe'],
    countries: ['*'],
    level: 'Bachelor · Master · PhD',
    funding: 'Varies by program',
    deadlineLabel: 'Dates depend on the program',
  },
  {
    id: 'fulbright',
    title: 'Fulbright Foreign Student Program',
    source: 'Fulbright',
    url: 'https://foreign.fulbrightonline.org/',
    focus: 'US graduate study and research for international applicants',
    fields: ['any'],
    regions: ['global'],
    countries: ['*'],
    level: 'Graduate',
    funding: 'Fully funded (typical)',
    deadlineLabel: 'Dates depend on your embassy',
  },
  {
    id: 'gates_cambridge',
    title: 'Gates Cambridge Scholarships',
    source: 'Gates Cambridge',
    url: 'https://www.gatescambridge.org/',
    focus: 'Full-cost postgraduate study at Cambridge',
    fields: ['any'],
    regions: ['global'],
    countries: ['*'],
    level: 'Postgraduate',
    funding: 'Fully funded',
    deadlineLabel: 'Usually October, December, or January',
  },
  {
    id: 'mandela_rhodes',
    title: 'Mandela Rhodes Scholarship',
    source: 'Mandela Rhodes Foundation',
    url: 'https://www.mandelarhodes.org/',
    focus: 'Postgraduate leadership awards for African citizens studying in South Africa',
    fields: ['any'],
    regions: ['africa', 'southern africa'],
    countries: ['*africa'],
    level: 'Honours · Master’s',
    funding: 'Tuition + stipend',
    deadlineLabel: 'Usually April',
  },
  {
    id: 'canon_collins',
    title: 'Canon Collins Trust Scholarships',
    source: 'Canon Collins Trust',
    url: 'https://www.canoncollins.org/scholarships/',
    focus: 'Postgraduate study support for southern African applicants',
    fields: ['any'],
    regions: ['southern africa', 'africa'],
    countries: [
      'botswana',
      'namibia',
      'south africa',
      'zambia',
      'zimbabwe',
      'malawi',
      'lesotho',
      'eswatini',
      'mozambique',
      'angola',
    ],
    level: 'Master’s · PhD',
    funding: 'Partial / full (program dependent)',
    deadlineLabel: 'See this year’s dates on their site',
  },
  {
    id: 'ashinaga',
    title: 'Ashinaga Africa Initiative',
    source: 'Ashinaga',
    url: 'https://www.ashinaga.org/en/what-we-do/ashinaga-africa-initiative/',
    focus: 'Full undergraduate support for orphaned students from Sub-Saharan Africa',
    fields: ['any'],
    regions: ['africa'],
    countries: ['*africa'],
    level: 'Undergraduate',
    funding: 'Fully funded',
    deadlineLabel: 'See this year’s AAI dates',
  },
  {
    id: 'yali',
    title: 'YALI Regional Leadership Center',
    source: 'Young African Leaders Initiative',
    url: 'https://yali.state.gov/',
    focus: 'Leadership training for young Africans (not a degree scholarship — high-impact fellowship)',
    fields: ['business', 'public', 'civic', 'any'],
    regions: ['africa'],
    countries: ['*africa'],
    level: 'Fellowship',
    funding: 'Program-funded',
    deadlineLabel: 'Dates depend on the cohort',
  },
  {
    id: 'erasmus_mundus',
    title: 'Erasmus Mundus Joint Masters',
    source: 'European Commission',
    url: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    focus: 'EU joint master’s with scholarships for international students',
    fields: ['any'],
    regions: ['global', 'europe', 'africa'],
    countries: ['*'],
    level: 'Master’s',
    funding: 'EMJM scholarship possible',
    deadlineLabel: 'See program catalogues (usually winter)',
  },
  {
    id: 'sweden_institute',
    title: 'Swedish Institute Scholarships',
    source: 'Swedish Institute',
    url: 'https://si.se/en/apply/scholarships/',
    focus: 'Fully funded master’s in Sweden for eligible countries',
    fields: ['any'],
    regions: ['global', 'africa'],
    countries: ['*'],
    level: 'Master’s',
    funding: 'Fully funded',
    deadlineLabel: 'Usually February',
  },
  {
    id: 'orange_knowledge',
    title: 'Orange Knowledge Programme (OKP)',
    source: 'Nuffic / Netherlands',
    url: 'https://www.studyinholland.nl/finances/orange-knowledge-programme',
    focus: 'Short courses and master’s for professionals from OKP countries',
    fields: ['any'],
    regions: ['africa', 'global'],
    countries: [
      'botswana',
      'namibia',
      'south africa',
      'zambia',
      'zimbabwe',
      'ghana',
      'kenya',
      'nigeria',
      'uganda',
      'tanzania',
      'rwanda',
      'ethiopia',
      'mozambique',
    ],
    level: 'Short course · Master’s',
    funding: 'Fully funded (typical)',
    deadlineLabel: 'Opens in application rounds',
  },
  {
    id: 'unesco_fellowships',
    title: 'UNESCO Fellowships',
    source: 'UNESCO',
    url: 'https://www.unesco.org/en/fellowships',
    focus: 'Short fellowships in education, science, and culture',
    fields: ['education', 'science', 'culture', 'any'],
    regions: ['global'],
    countries: ['*'],
    level: 'Fellowship',
    funding: 'Varies',
    deadlineLabel: 'Dates depend on each call',
  },
  {
    id: 'african_union',
    title: 'African Union Education Opportunities',
    source: 'African Union',
    url: 'https://au.int/en/education',
    focus: 'Continental education and mobility opportunities for African students',
    fields: ['any'],
    regions: ['africa'],
    countries: ['*africa'],
    level: 'Various',
    funding: 'Program dependent',
    deadlineLabel: 'Dates depend on each call',
  },
  {
    id: 'scholarshipportal',
    title: 'ScholarshipPortal (Europe)',
    source: 'ScholarshipPortal',
    url: 'https://www.scholarshipportal.com/',
    focus: 'Searchable European university scholarships',
    fields: ['any'],
    regions: ['europe', 'global'],
    countries: ['*'],
    level: 'Bachelor · Master · PhD',
    funding: 'Varies',
    deadlineLabel: 'See each listing for dates',
  },
  {
    id: 'mo_ibrahim',
    title: 'Mo Ibrahim Foundation Leadership / Governance',
    source: 'Mo Ibrahim Foundation',
    url: 'https://mo.ibrahim.foundation/',
    focus: 'Leadership and governance programs focused on Africa',
    fields: ['public', 'governance', 'business', 'any'],
    regions: ['africa'],
    countries: ['*africa'],
    level: 'Fellowship · Master’s partners',
    funding: 'Program dependent',
    deadlineLabel: 'See the foundation’s site for dates',
  },
  {
    id: 'aga_khan',
    title: 'Aga Khan Foundation International Scholarship',
    source: 'Aga Khan Foundation',
    url: 'https://the.akdn/en/what-we-do/developing-human-capacity/education/international-scholarships',
    focus: 'Postgraduate awards for outstanding students from select developing countries',
    fields: ['any'],
    regions: ['africa', 'global'],
    countries: ['*'],
    level: 'Master’s · PhD',
    funding: 'Loan-grant hybrid typical',
    deadlineLabel: 'Usually March',
  },
  {
    id: 'botswana_hrdc',
    title: 'Botswana Human Resource Development Council / DTEF pathways',
    source: 'Botswana HRDC',
    url: 'https://www.hrdc.org.bw/',
    focus: 'National skills and sponsorship pathways for Botswana citizens',
    fields: ['any'],
    regions: ['botswana', 'southern africa'],
    countries: ['botswana'],
    level: 'Various',
    funding: 'National sponsorship (where open)',
    deadlineLabel: 'Watch ministry or HRDC notices',
  },
  {
    id: 'ub_scholarships',
    title: 'University of Botswana Scholarships & Aid',
    source: 'University of Botswana',
    url: 'https://www.ub.bw/',
    focus: 'Institutional awards and notices for study at UB',
    fields: ['any'],
    regions: ['botswana', 'southern africa'],
    countries: ['botswana', 'namibia', 'south africa', 'zambia', 'zimbabwe'],
    level: 'Undergrad · Postgrad',
    funding: 'Varies',
    deadlineLabel: 'Watch faculty notices',
  },
]

const AFRICA_COUNTRIES = [
  'botswana',
  'namibia',
  'south africa',
  'zambia',
  'zimbabwe',
  'malawi',
  'lesotho',
  'eswatini',
  'mozambique',
  'angola',
  'nigeria',
  'ghana',
  'kenya',
  'uganda',
  'tanzania',
  'rwanda',
  'ethiopia',
  'senegal',
  'cameroon',
  'egypt',
  'morocco',
  'tunisia',
  'ivory coast',
  "côte d'ivoire",
  'africa',
]

export function normalizeCountry(country = '') {
  return String(country).trim().toLowerCase()
}

export function isScholarshipEligible(program, countryRaw) {
  const country = normalizeCountry(countryRaw)
  if (!country) return true // show global set until country set

  const list = program.countries || []
  if (list.includes('*')) return true
  if (list.includes('*africa')) {
    return AFRICA_COUNTRIES.some((c) => country.includes(c) || c.includes(country))
  }
  if (list.some((c) => country.includes(c) || c.includes(country))) return true

  // Region fallback via program.regions handled by scorer boosts; still allow global-ish
  if (list.length === 0 && (program.regions || []).includes('global')) return true
  return false
}
